language: python
matrix:
  include:
   - os: linux
     python: 3.6


before_install:
 - "pip install poetry"  # Maybe install something here later on for testing etc.

install:
 - "poetry install"

script:
 - "make test"
 - "make package"
